language: node_js
sudo: false
arch:
  - amd64
  - ppc64le
node_js:
  - "10"
  - "8"
  - "6"
  - "11"
before_install:
  - "npm install -g npm"
script: "npm test"
notifications:
    slack: npm-inc:kRqQjto7YbINqHPb1X6nS3g8
